spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: registration-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/registration/**
            - id: user-current
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/user/current
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${LHOST}:8761/eureka/

server:
  port: 8202

jwt:
  accessTokenSecret: ${ACCESS_TOKEN_SECRET}
  cookieName: access_token

web:
  frontendUrl: http://${LHOST}:5173