spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
                - Path=/api/v1/internal/registration/**
                - Path=/api/v1/addresses/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#  loadbalancer:
#    ribbon:
#      enabled: false  # Disable Ribbon, use Spring Cloud LoadBalancer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${LHOST}:8761/eureka/

server:
  port: 8202

jwt:
  secret: ${JWT_SECRET}
  cookieName: jwt
  maxAge: 36000000
  secure: false

web:
  frontendUrl: http://${LHOST}:5173