spring:
  data:
    redis:
      host: redis-19055.c135.eu-central-1-1.ec2.cloud.redislabs.com
      port: 19055
      username: default
      password: ${REDIS_PASSWORD}
      timeout: 2000ms

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_SVC}:${DISCOVERY_SERVER_PORT}/eureka/