spring:
  data:
    redis:
      host: ${REDIS_SVC}
      port: ${REDIS_PORT}
      timeout: 2000ms

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${DISCOVERY_SERVER_SVC}:${DISCOVERY_SERVER_PORT}/eureka/