spring:
  data:
    redis:
      host: localhost
      port: 6380
      timeout: 2000ms

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/