spring:
  datasource:
    url: jdbc:postgresql://${LHOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    port: ${POSTGRES_PORT}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true
    clean-disabled: true
  data:
    redis:
      host: ${LHOST}
      port: ${REDIS_PORT}
      timeout: 2000ms

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${LHOST}:8761/eureka

server:
  port: 8084