spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      access: READ_ONLY
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    com.aziz.notification_service: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

server:
  port: 8087

kafka:
  topic:
    user-registered: user.registered
    otp-verification: otp.verification
    order-created: order.created
    order-payment: order.payment
    payment-completed: payment.completed