spring:
  cassandra:
    keyspace-name: ${CASSANDRA_KEYSPACE}
    username: ${CASSANDRA_USERNAME}
    password: ${CASSANDRA_PASSWORD}
    schema-action: CREATE_IF_NOT_EXISTS
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.type.mapping: "com.aziz.user_service.kafka.events.UserRegisteredEvent:com.aziz.notification_service.kafka.events.UserRegisteredEvent,com.aziz.user_service.kafka.events.OtpVerificationEvent:com.aziz.notification_service.kafka.events.OtpVerificationEvent,com.aziz.order_service.kafka.events.OrderCreationEvent:com.aziz.notification_service.kafka.events.OrderCreationEvent,com.aziz.payment_service.kafka.events.PaymentSuccessEvent:com.aziz.notification_service.kafka.events.PaymentSuccessEvent"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER}:${DISCOVERY_SERVER_PORT}/eureka/