spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      access: READ_ONLY
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    com.aziz.order_service: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

server:
  port: 8087

kafka:
  topic:
    payment-completed: payment.completed
    order-payment: order.payment

# paymob:
#   apiKey: ${PAYMOB_API_KEY}
#   secretKey: ${PAYMOB_SECRET_KEY}
  # publicKey: ${PAYMOB_PUBLIC_KEY}
  # integrationId: ${PAYMOB_INTEGRATION_ID}
  # iFrameId: ${PAYMOB_IFRAME_ID}
  # hmacSecret: ${PAYMOB_HMAC_SECRET}
  # baseUrl: ${PAYMOB_BASE_URL}