spring:
  data:
    mongodb:
      host: ${LHOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DB}
      authentication-database: admin
    elasticsearch:
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      uris:
        - http://${LHOST}:${ELASTICSEARCH_HTTP_PORT}