spring:
  mongodb:
    host: ${MONGO_HOST}
    database: ${MONGO_DATABASE}
    username: ${MONGO_USER}
    password: ${MONGO_PASSWORD}
    authentication-database: admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER}:${DISCOVERY_SERVER_PORT}/eureka/