spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      database: ${MONGO_DATABASE}
      user: ${MONGO_USER}
      password: ${MONGO_PASSWORD}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER}:${DISCOVERY_SERVER_PORT}/eureka/