spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: aziz
      password: aziz333
      database: products
      authentication-database: admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/