spring:
  datasource:
    url: jdbc:postgresql://${LHOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    mongodb:
      uri: mongodb://${LHOST}:${MONGO_PORT}/${MONGO_DB}
    redis:
      host: ${LHOST}
      port: ${REDIS_PORT}
      timeout: 2000ms