spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      access: READ_ONLY
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    com.aziz.user_service: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

server:
  port: 8082

kafka:
  topic:
    otp-verification: otp.verification
    user-registered: user.registered